[build]
  command = "npm run build:netlify"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

# We're not using the Next.js plugin with static export
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# These redirects ensure client-side routing works with static export
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  included_files = [".env.local"]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "nextjs"